### ISSUE TITLE
the result is not like what u said

### ISSUE THREAD

**Issue by csrgxtu** [macournoyer/neuralconvo#58]
i use this command train:

``` bash
th train.lua --dataset 50000 --hiddenSize 1000
```

though it is CPU, but after weeks, It trained, and test like this:
![result](https://github.com/csrgxtu/Drogo/blob/master/img/result.png?raw=true)

**Comment by CodePothunter** [comment]
yep... You should know this author is not that of the paper and the data set is also different... Actually, I doubted that the samples given by Google could be reproduced, because it looked so "intelligent"!

**Comment by macournoyer** [comment]
Sadly, neither can I reproduce the results anymore :/ I added a warning about this in the README.

The cause seems to be a change in one of dependencies. I don't know which one. But I'm currently working on a new implementation based on [harvardnlp/seq2seq-attn](https://github.com/harvardnlp/seq2seq-attn).

**Comment by csrgxtu** [comment]
this always confuse me, cause people say that a algorithm can achieve 97% accuracy, but in reality in my situation, it is only 70%.

**Comment by nabihach** [comment]
@macournoyer, any news about your new implementation? Eagerly looking forward to it.

**Comment by deepcoord** [comment]
@macournoyer I got the same issue as @CodePothunter mentioned when using harvardnlp/seq2seq-attn.
Can anyone get the reasonable responses using the existing open source implementations?
